### ISSUE TITLE
Skip send-oob-otp page conditionally / Revert #795

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#1039]
When any of the following condition holds, skip send-oob-otp page

1. This is primary authentication.
2. This is secondary authentication and oob-otp is the only choice.

**Comment by chpapa** [comment]
I think the way to fix maybe is to revert #795 (#811 PR)

I just tried on https://bencheng-test.authgear-staging.com

The implementation seems just not working as we described:

Configuration:
* enabled both TOTP and OOB_SMS as my 2FA

Observed behaviour:
* Login with OOB_SMS: being asked to consent sending SMS
* MFA, no seleciton screen, just show TOTP by default, and have a small link say “Send code to +…… instead via SMS”
* When I click on that small link, it sends the SMS directly, with no confirmation page.

#795 say "Require user interaction before sending MFA code", it seems the actual behaviour is "Require user interaction before sending OTP code"

So it seems the problem is #795 is just a wrong implementation to the OOB login, but not OOB as 2FA, maybe the simple solution is just to revert #795

**Comment by louischan-oursky** [comment]
Even if we revert #795, we still miss the MFA selection page.

**Comment by chpapa** [comment]
@louischan-oursky so forget the MFA selection page first, use the current one (show a default, and alternative MFA in small links)

Maybe we can leave these very detailed customisation (MFA selection page) into later implementation of "flow" or something else.

**Comment by carmenlau** [comment]
> When I click on that small link, it sends the SMS directly, with no confirmation page.

I think this behaviour is expected? Since user chose "Send code to +…… instead via SMS" already and this is the user interaction. 

So maybe we should update the "send-oob-otp" page should only be shown when user have more than 1 secondary authentication and oob is the default mfa (so user can choose alternative MFA in small links in "send-oob-otp" page)?

**Comment by chpapa** [comment]
> So maybe we should update the "send-oob-otp" page should only be shown when user have more than 1 secondary authentication and oob is the default mfa (so user can choose alternative MFA in small links in "send-oob-otp" page)?

If not complicated I think this is ok

maybe ui wise see how to emphasise the CTA and make button large like “Send the SMS code”

**Comment by carmenlau** [comment]
Finally we removed the "send-oob-otp" page completely in https://github.com/authgear/authgear-server/pull/1051
