### ISSUE TITLE
Unknown error when saving config and templates at the same time

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#1109]
![image](https://user-images.githubusercontent.com/16920209/113240307-0b4ead80-92df-11eb-9458-d4d2844b3605.png)

Only happens occasionally and no problem after requesting to update blocklist/allowlist config again

**Comment by carmenlau** [comment]
I found that error occurs occasionally when we perform action that needs save config and templates at the same time. In the saving logic, we first list the secret and then update it. I suspect if we call two updates at the same time, the second call may listed the outdated secret, since the first call updated it.

We can try update portal code to call the update one by one and see if it can solve the problem. 

Update secret logic:
https://github.com/authgear/authgear-server/blob/cb2a0d1b2c3e9b6317a9f62f219c38c65f9b7d59/pkg/portal/service/config.go#L155

**Comment by mr9dollars** [comment]
Cannot reproduce on staging anymore. Would close.
