### ISSUE TITLE
Login with biometrics on mobile SDK would create two sessions

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#1111]
Tested with Android and iOS example app
1. Login with biometrics
2. See two session are created. One with login kind and another one with Authorized App kind
3. If logout, only the session with Authorized App kind is deleted.

![image](https://user-images.githubusercontent.com/16920209/113263661-a017d200-9304-11eb-855e-62a773ea37d3.png)

**Comment by louischan-oursky** [comment]
This is because we are using the interaction graph to run the authentication. The IdP session is always created as a side effect.

Planned approach

- Add a flag in the interaction intent to inform the do-create-session-node not to create the session
- Statically create the session attrs for anonymous user authentication and biometric authentication
