### ISSUE TITLE
[Portal] User search and sort

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#1132]
**User search and sort**
- [x] User Table
- [x] Allow to search user through email, username, user id or phone number
- [x] Allow to sort user through last login, signed up

**Comment by louischan-oursky** [comment]
# Choice of search engine

Elasticsearch

# Deployment of Elasticsearch

- Local: Official docker image `docker.elastic.co/elasticsearch/elasticsearch:7.12.0` with [single node cluster](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode)
- Staging: [Official helm chart](https://github.com/elastic/helm-charts/tree/master/elasticsearch)
- Production: [Official helm chart](https://github.com/elastic/helm-charts/tree/master/elasticsearch)

# Mapping

```json
{
  "properties": {
    "app_id": { "type": "keyword" },
    "id": { "type": "keyword" },
    "created_at": { "type": "date" },
    "updated_at": { "type": "date" },
    "last_login_at": { "type": "date" },
    "is_anonymous": { "type": "boolean" },
    "is_verified": { "type": "boolean" },
    "is_disabled": { "type": "boolean" },
    "email": { "type": "keyword" },
    "preferred_username": { "type": "keyword" },
    "phone_number": { "type": "keyword" }
  }
}
```

# Operations

## `authgear search reindex <app-id>`

Re-index all data for the given app.

## `authgear search reindex --all`

Re-index all data for all apps.
Mainly for initial deployment, or we have breaking changes on the mapping.

## Re-index a user

- When a user is created.
- When a user is disabled.
- When a user is enabled.
- When a user is promoted.
- When an identity of a user is added.
- When an identity of a user is updated.
- When an identity of a user is deleted.
- When an identity of a user is verified.

# Search

```json5
{
  "query": {
    "bool": {
      "filter": [
        { "term": { "app_id": "APP_ID" } }, // 1
      ],
      "should": [
        { "term": { "email": "KEYWORD" } }, // 2
        { "term": { "preferred_username": "KEYWORD" } }, // 3
        { "term": { "phone_number": "KEYWORD" } }, // 4
        {
          "regexp": { // 5
            "email": {
              "value": "@KEYWORD$",
              "case_insensitive": true
            }
          }
        },
        {
          "regexp": { // 6
            "phone_number": {
              "value": "KEYWORD$"
            }
          }
        }
      ]
    }
  },
  "sort": [ // 7
    "_score",
    { "created_at": { "order": "asc" } },
    { "last_login_at": { "order": "asc" } }
  ]
}
```

- 1: The search is always app-specific.
- 2: Exact match on any email addresses the user has.
- 3: Exact match on any usernames the user has.
- 4: Exact match on any phone numbers the user has.
- 5: If KEYWORD is a valid domain name, then match any email addresses of that domain. For example, if KEYWORD is `example.com`, then the result will contain users with `@example.com` email addresses.
- 6: If KEYWORD is digits only, then match any phone numbers ending with KEYWORD. For example, if KEYWORD is `99887766`, then the result will contain users with `+85299887766` phone number.
- 7: If no sorting is specified, sort by `_score`. Otherwise, sort by `created_at` or `last_login_at`, `asc` or `desc`.


@carmenlau Some initial planning on the search feature. See if you have any concerns?

**Comment by louischan-oursky** [comment]
```
ERROR: [1] bootstrap checks failed. You must address the points described in the following [1] lines before starting Elasticsearch.
bootstrap check failure [1] of [1]: Transport SSL must be enabled if security is enabled on a [basic] license. Please set [xpack.security.transport.ssl.enabled] to [true] or disable security by setting [xpack.security.enabled] to [false]
```
