### ISSUE TITLE
Unable to login with Microsoft ADFS accounts on iOS 12

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1366]
Build: Dev
Device: iPhone 6s (12)

After inputting correct credentials, the end-user is redirected to setting page. 
Closing the in-app browser will result in "Failed to Sign Up / Login" message.

**Comment by fungc-io** [comment]
Device: iPhone 6s (12)
Platform: React Native

I tried login with the demo-react-native app

Login with email was successful.

However when I try "Login with Google",
This Error message occurred when redirected to the app
![IMG_0917](https://user-images.githubusercontent.com/15207470/126438915-61a3f236-a76f-4bc4-b95f-45044ebbe1a1.PNG)

After that, triggering "Authenticate" again will show the continue screen with my google account
![IMG_0919](https://user-images.githubusercontent.com/15207470/126439074-973b4d72-67cf-4676-b743-4d2da6f309d9.PNG)

**Comment by louischan-oursky** [comment]
This bug is due to the bug of Webkit (i.e. Safari) on some older iOS 12.x versions. On iOS 12.4 and above, the webkit bug have been fixed. So this bug only affects device on iOS 12.0 through iOS 12.3.

The detailed bug description is documented by Auth0. https://community.auth0.com/t/authentication-broken-on-asp-net-core-and-safari-on-ios-12-mojave/16077 and https://community.auth0.com/t/authentication-broken-on-asp-net-core-and-safari-on-ios-12-mojave-take-2/19104 . The related webkit issue is here https://bugs.webkit.org/show_bug.cgi?id=188165

Since this bug has been fixed by a minor version of iOS 12.x, I am not going to spend effort on fixing this issue.
