### ISSUE TITLE
Back after few OTP error should go to previous step

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-server#143]
## What to do
If a user does the following: 
1. Sign up by input phone no. => Verify SMS and click to send SMS
2. Enter code => Wrong 
3. Enter Code => Wrong
4. Enter Code 

if user at step 4 and press back should go to step 1 instead of step 3

## Technical Requirement
The Web AuthUI should remain usable without Javascript enabled, so this feature should gracefully reduce to step 4 go back to step 3 if JS was disabled / blocked.

**Comment by chpapa** [comment]
@keithtkl updated description

**Comment by louischan-oursky** [comment]
Discussed with @kiootic we are going to try the following approach.

We would like to keep the property of having immutable state (`x_sid` keeps changing for each form submission).

The root cause of this issue is that the browser manages the back stack for us. But the behavior in case of form submission failure is not desirable. We want to skip adding back stack entry if the form submission results in error.

If JavaScript is enabled, we are going to use HTML5 history API to manipulate the back stack. In this case, the content of the page and the URL in the address bar is not in sync anymore. We need to introduce a mechanism to keep them in sync.

We are going to add the intended URL as a meta tag in the head of the page. Doing so allows to know whether we are showing the content indicated by the URL in the address bar.

- [ ] Update the XHR form submission handler to manipulate history.
  - [ ] Determine whether the form submission is failure or success
    - [ ] Currently we rely on the fact that failed form submission redirects to the same path. So if the path remains unchanged, it is a form submission failure.
  - [ ] Use `history.replaceState` to update the URL in the address bar in case of form submission failure.
  - [ ] Use `history.pushState` to update the URL in the address bar if the form submission is successful.
- [ ] Add a new event handler to listen `popstate`.
  - [ ] check if the intended URL in the meta tag matches the URL in the address bar. If not match, reload the page.
