### ISSUE TITLE
[User Portal, User details] Birthday date picker is not visible in dark theme as it is black

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1641]
ui/minor

### Environment
Device: Chrome on Mac
Build: staging

### Description
Birthday date picker is not visible in dark theme as it is black

### Steps:

1. Login to app user portal
2. Click My Profile, More, Birthday edit icon
4. See current date picker not visible

### Expected behaviour:
Date picker should be white in dark theme.

Future enhancement suggestion, also show datepicker when user click on the date nubmer, as in admin portal

### Screenshot:
![image](https://user-images.githubusercontent.com/4337525/141761648-54691f89-5071-4b44-b1dd-1601233e3bda.png)

**Comment by fungc-io** [comment]
This is how the datepicker input looks on Android Chrome
The UX is ok because the date picker panel will open when the user tap on the field.
Only a UI issue in which the field doesn't take up the card width.
![Birthdate Android Chrome](https://user-images.githubusercontent.com/15207470/141924661-6bfd9759-c633-4109-9c83-11233aca472e.jpg)

**Comment by fungc-io** [comment]
The UI and UX are great on iOS 14 & 15 Safari
![IMG_4647](https://user-images.githubusercontent.com/15207470/141926958-c6e845c1-67a8-4938-b0ad-80d3e6527eb6.PNG)
