### ISSUE TITLE
2FA config turn on automatically

### ISSUE THREAD

**Issue by matthew-oursky** [authgear/authgear-server#1705]
The 2FA option comes back with no reason after changing other settings in the Authgear portal.

#### Environment
Staging

#### Expected Results
Changing other settings should not turn on 2FA.

#### Actual Results
2FA comes back with no reason.

#### Steps to reproduce
1. Disable all "Secondary Authenticator" options in "Authentication > Authenticators"
2. Change other settings in the Authgear portal.
3. See "Authentication > Authenticators > Authenticator Apps / Devices" option turned on with no reason.

**Comment by louischan-oursky** [comment]
The root cause of this bug is due to the the behavior of `omitempty`. In this case, an omitted `secondary_authenticators` and an empty slice of `secondary_authenticators` mean different things, but `omitempty` treat both the same. Currently it is possible to set `secondary_authenticators` to an empty slice. However, when it is serialized, it is omitted by `encoding/json`, leading to the ambiguity.

Since fixing `secondary_authenticators` is impossible, I propose we add a new variant `disabled` to `secondary_authentication_mode` to turn off MFA explicitly.

@carmenlau @fungc-io Thoughts?

**Comment by louischan-oursky** [comment]
I just realized we have an hidden, unimplemented option call `if_requested`. Let's take this change to remove `if_requested` and add `disabled`. What do you guys think?

**Comment by louischan-oursky** [comment]
The issue will be solved in two phases.

In the first phase, the following changes are included:

- Add `disabled` as a new option
- Deprecate `if_requested`. It becomes equivalent to `disabled`. The option becomes hidden in the dropdown. Existing value is shown as `Disabled (Deprecated)`.
- (TBC) Revamp the configuration UI so that identity is more closely related to primary authenticators, while secondary authenticators are relevant only when mode is NOT `disabled`
- Add a re-runnable migration command to turn `if_requested` to `disabled`, and set mode to `disabled` if `secondary_authenticators` is an empty slice.

In the second phase, the following changes are included:

- Remove `if_requested`
- Do NOT allow empty slice in `secondary_authenticators`

**Comment by fungc-io** [comment]
The `emitempty` bug mentioned in https://github.com/authgear/authgear-server/issues/1705#issuecomment-1003904462 found to be fixable.

In our discussion, we found the re-arrangement proposed in #1715 is not a good solution to improve IA and UX. Further re-design is needed to improve the configuration experience. Which should be put into the next big UI overhaul project.

Therefore, we decide to keep the the existing navigation but make some small changes in `/authentication/authenticators` to  fix this issue.

New:

> ## Authenticators

> Description: Configure how you want users to authenticate themselves (such as Password), and any secondary authenticator requirements

> ## Primary Authenticator (Unchanged)

> ## Secondary Authenticator
> 
> (Dropdown) Require Secondary Authenticator
> > Disabled
> > Required if user has Secondary Authenticator
> > Always Required
> 
> (list of Secondary Authenticator)
> (toggle) Disable "Do not ask again on this device" for the Secondary Authenticator

> ## Recovery Code
> In the case of losing access to the Secondary Authenticators, the end-user can recover their account by using the Recovery Codes
> 
> (number input) Number of Recovery Code 
> (toggle) Allow user to retrieve or regenerate recovery code again
