### ISSUE TITLE
Research on Xamarin Wrapper for the native SDKs

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#1744]
A Xamarin SDK is needed.
Research the feasibility of building a simple wrapper as a bridge to native Authgear SDKs and see how much effort is needed.

**Comment by louischan-oursky** [comment]
# iOS

- Build a .framework written in Swift
- Create a Binding Library for that .framework
- The method signature must be `doSomething(_ arg1: Arg1, arg2: Arg2)`, otherwise, the method name will become `doSomethingWithArg1`
- It is possible to expose `Error`

# Android

- Build a .aar written in Java
- Create a Binding Library for that .aar
- Due to type erasure of Java, the completion interface always have the type `void invoke(java.lang.Object result, java.lang.Throwable error)`

**Comment by louischan-oursky** [comment]
- Xamarin.Essentials has API to open authentication webview: https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=android

**Comment by fungc-io** [comment]
A Xamarin SDK is developed: https://github.com/authgear/authgear-sdk-xamarin
This issue is obsoleted
