### ISSUE TITLE
[User Portal, Authentication] Cannot receive email verification when signing up/logging in if `Accept-Language` is `zh-hk`

### ISSUE THREAD

**Issue by stanleylhs** [authgear/authgear-server#1809]
bug/critical

## Background:
- Device / Browser (OS version): Chrome on win 11
- Build: staging-2022-02-08.0
- Testing site: demo-enterprise

## Description:
When the user signs up or logs in to the site via email, user will not receive an email verification if `Accept-Language` from browser is `zh-hk` at the top

## Steps to reproduce:
1. Switch the browser webpage display language to Chinese (Hong Kong) [zh-hk]
2. Login/Sign up via email
3. See no email verification received

## Expected result:
Should receive email verification code

## Screenshot:
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/4337525/154889395-e7d45699-8dfb-4524-83ec-0e483f6430ba.png">

![image](https://user-images.githubusercontent.com/4337525/154889262-4a97c34c-987f-486c-9f75-d4376fd61520.png)

Video: en-US success, zh-HK no email

https://user-images.githubusercontent.com/4337525/154889220-c3f47185-dd08-4399-8846-ff92015ad38f.mov

**Comment by fungc-io** [comment]
@stanleylhs Can you help try if this problem only shown in the `demo-enterprise` project or in others too?

**Comment by stanleylhs** [comment]
> @stanleylhs Can you help try if this problem only shown in the `demo-enterprise` project or in others too?

Will try later today

**Comment by carmenlau** [comment]
The email sending problem is caused by the incorrect email sender in the `zh-HK` language. In the staging cluster, we only overwrite the email sender in the English custom fs level `translation.json`. So in the original matching mechanism, the build-in ` zh-HK` translation will be matched when the users visit the `zh-HK` site which the email sender is incorrect.

After discussion, we decide to introduce a new concept of app-specific keys. For those translations which are application specific (e.g. app name, email sender...etc), if the translations are provided in the higher FS level (e.g. application overwrite), we should always use the user's provided value, no matter if their languages are matched or not.
