### ISSUE TITLE
[Bug][WhatsApp OTP] "Open in WhatsApp" is not working on iOS

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2126]
**Describe the bug**
After clicking "Open in WhatsApp", the screen stuck at api.whatsapp.com. The users will need to tap the back button in the in-app browser to complete the login flow.

**Authgear Version**
 - Version: SaaS @ 2022-06-20
 - iOS demo app

**To Reproduce**
1. Login/Signup with Whatsapp
2. Click on "Open in WhatsApp"
3. Whatsapp chat screen is opened, click send. The go back to the app.
4. See the in-app browser in the "api.whatsapp.com" screen

**Expected behavior**
See "Message received" in AuthUI in step 4.

**Client Env (if applicable, please complete the following information):**
 - Device: iPhone 13 mini
 - iOS 15.5

**Comment by chpapa** [comment]
iOS latest version will remember the behaviour of deep links:

1. If the users long tap the link, and click `Open`, it will redirect to Safari; And it will be remembered
2. Similarly, if click `Open in "Whatsapp"`, it will redirect to Whatsapp immediately

So we can't really "fix" this, unless we figure out an alternative way...

**Comment by carmenlau** [comment]
In today product meeting, we have discussed 2 solutions for the problem which is using whatsapp custom url scheme. But the problem is the custom url scheme of whatsapp doesn't support providing the recipient phone number. Only universal link does :(

https://faq.whatsapp.com/563219570998715/?locale=en_US

I tried in `ASWebAuthenticationSession`, I can open whatsapp successfully via custom url scheme but no recipient is selected.

My testing code: https://github.com/carmenlau/authgear-server/tree/whatsapp-custom-url-scheme
