### ISSUE TITLE
Admin API list users by page

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#218]

**Comment by kiootic** [comment]
Since portal requires offset-based pagination (instead of infinite scroll), a cursor-based pagination mechanism would be hard to consume at portal side. We would use offset-based pagination in admin API instead. If admin API consumer would like to have accurate pagination for enumeration (offset-based pagination may be inaccurate since the entry may 'jump' around due to sort order), the sort order should be set to 'created_at', which should be stable.
