### ISSUE TITLE
When empty data in Analytics page, show explaination

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2254]
For a new project, the analytics page is very empty. 
After the user has tried signup for a few users, the page is still no data because there is a delay in data collection.

If there is not data, show a warning message bar (yellow) that says:

"The selected dates have no data. Reporting is not realtime. The numbers are delayed up to 24 hours."

So they don't think the page is broken.

**Comment by carmenlau** [comment]
Seems the message is not very accurate, for the dates that we show in the analytics page are past already. They are empty because the project is newly created, they should not have data before the project is created. 

Should we change it a bit like, show the warning message if the project is created within 24 hours. The message will become something like "The analytics portal shows your project's activities. The numbers are delayed up to 24 hours.". 
Or we can always show this message since this is true for all cases.

Thought?
