### ISSUE TITLE
Icon and Text color of disabled primary button

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2316]
@andychow326 @carmenlau 

Current implementation:

Icon is much darker than the text which look ugly, and the text is too light to read.

<img width="121" alt="Screenshot 2022-08-15 at 17 47 38" src="https://user-images.githubusercontent.com/15207470/184678799-09b003c1-c452-498a-b8ee-6ce32b73738d.png">

Is this the default in Fluent React?
Coz in the v8 demo site, the icon and text have the same color value:
https://fabricweb.z5.web.core.windows.net/oufr/8.88.0/#/examples/button

**Comment by carmenlau** [comment]
We set the theme color here: https://github.com/authgear/authgear-server/blob/master/portal/src/system-config.ts

But the actual problem is not about the color setting, the disabled primary button has lighter text color. See the screenshot below:
<img width="787" alt="Screenshot 2022-08-15 at 10 06 21 pm" src="https://user-images.githubusercontent.com/388892/184720707-d947694f-51f7-45b1-9bb5-05a1a95af659.png">
The second one is the disabled primary button and the latter one is the disabled default button.

So, to fix it we can change the usage of the primary button and don't use the primary style when it is disabled. e.g.
```
<DefaultButton
      primary={!disabled}
      disabled={disabled}
      ...
/>
```
We can wrap `PrimaryButton` and use the custom one in the whole portal.

**Comment by louischan-oursky** [comment]
Maybe we can override the disabled text color with theme. Here is the styles of BaseButton https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Button/BaseButton.styles.ts But I cannot figure out why the disable text color of primary button is lighter.
