### ISSUE TITLE
Support authentication with Primary and Secondary Authenticator at once

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#233]
Similar to Bank / AWS login system, verify primary and secondary authenticator at once, instead of showing secondary authenticator only after primary authenticator is verified.

**Comment by louischan-oursky** [comment]
This is quite complex because the combination of primary and secondary authenticator will complicate the UI. I have another idea. What about we do not report the authentication result of the primary authentication and head straight to secondary authentication? After we have collected primary and secondary authentication information from the user, we perform both and report a single result (just tell the user invalid credentials but do not tell them which one is incorrect).

**Comment by chpapa** [comment]
> What about we do not report the authentication result of the primary authentication and head straight to secondary authentication? After we have collected primary and secondary authentication information from the user, we perform both and report a single result (just tell the user invalid credentials but do not tell them which one is incorrect).

This sounds like exactly what the description is about? :)

**Comment by chpapa** [comment]
This should be obsoleted #2749 (or being considered as well)
