### ISSUE TITLE
Fix ScreenNav interpreted link

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#2422]
The interpreted link (the link interpreted by the browser and be shown at the bottom of the window when a link is hover) is incorrect sometimes.

**Comment by andychow326** [comment]
@louischan-oursky I found out that react-router v6 supports the use of `basename` which can be used to define relative root of route. (https://reactrouter.com/en/main/routers/browser-router)

How about we implement a dynamic `basename` in the router component?

**Comment by louischan-oursky** [comment]
It seems like we can use <Router> to have multiple entrypoints. Can you take a look at it? https://reactrouter.com/en/main/routers/router

**Comment by andychow326** [comment]
> It seems like we can use `<Router>` to have multiple entrypoints. Can you take a look at it? https://reactrouter.com/en/main/routers/router
> 
> * Investigate whether nesting Router under BrowserRouter is a legitimate usage.
> * Investigate how to render a link relative to the root, instead of basename. For example, is it possible to render `/projects` if we are currently at `/apps/<APP_ID>/configuration/authentication` when using `<Router basename>`

- It seems that we cannot embed another `<Router>` into `<BrowserRouter>` in the v6 of react-router as the following error message appears:
    ```
    Error: You cannot render a <Router> inside another <Router>. You should never have more than one in your app.
    ```

- As far as i know, if we are using `<Router basename>`, it might not be able to render the route out of the `basename`. For example, for the `<Router basename="/project/:appID">`, it cannot render the route "/project" or "/". If we really want to do so, we might need to use the `anchor` tag instead of using react-router to resolve the url for us.

**Comment by louischan-oursky** [comment]
So what is the conclusion? Stick with the changes of the outstanding PR and use absolute paths everywhere?
