### ISSUE TITLE
Percel compiler crashes in development mode

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2457]
When working in local development, the percel compiler of the Authgear portal will become slow and then crashed after about 1 hour of working. The developers need to restart their machines to continue their work. This is slowing down the development.

Please investigate and see what went wrong @andychow326

**Comment by andychow326** [comment]
After a few hours of testing, I have figured out the potential reason for the portal timed out issue. The main reason is on the application `Docker for Mac` instead of `Parcel`. After checking for the resource usage by this application, it will produce a process called `qemu-system-aarch64` and occupy a huge amount of memory. The server or the nginx reverse proxy may not work well after >5000 requests.

## Steps to reproduce
1. Run everything in development
2. Use [Apache HTTP server benchmarking tool](https://httpd.apache.org/docs/2.4/programs/ab.html) to generate >5000 requests on portal
3. May encounter timeout issue during the test
4. Try using browser to browse the portal page
5. The page takes unreasonable time to response or may see blank page

## Workaround steps
1. Quit the `Docker for Mac` application and wait for it to be killed
2. Restart the `Docker for Mac` application
