### ISSUE TITLE
[Firefox, Ethereum & NFT, Login] Unable to detect installed MetaMask Firefox Extension during sign-in/up

### ISSUE THREAD

**Issue by JasonNS1425** [authgear/authgear-server#2507]
bug critical, reported by qa

Build: Staging-29Sep2022
Device: Chrome, Firefox, Edge on win 11

Steps:
1. Install the MetaMask extension in the Firefox browser (e.g. 
2. Visit any Ethereum-login-enabled login portal in the browser
3. Log in using the MetaMask account
4. See the MetaMask extension not detected error

Expected behavior:
Should be able to log in using the MetaMask account on all browsers supported by MetaMask

Screenshots:

https://user-images.githubusercontent.com/67095825/193016662-9b646d70-243d-4a31-bd33-58447e5229a2.mp4

**Comment by hochiw** [comment]
This is due to the strict CSP we have for authgear to prevent script injection. This also happens with Safari (i.e metamask mobile), see how we want to handle this. @louischan-oursky 

refs 
https://github.com/MetaMask/detect-provider/issues/31
https://github.com/authgear/authgear-server/blob/master/pkg/lib/web/csp.go

**Comment by louischan-oursky** [comment]
The team decided to make the following changes

- Relax CSP (or disable CSP, if necessary) on SIWE pages
- Keep login page CSP enabled

**Comment by hochiw** [comment]
Interesting found on the CSP [draft standard](https://w3c.github.io/webappsec-csp/#allow-all-inline),

`
If expression matches the nonce-source or hash-source grammar, return "Does Not Allow".
`
Since nonce is provided for authgear's CSP, `unsafe-inline` will be ignored, so we will need to not provide nonce for the SIWE pages.
