### ISSUE TITLE
Support JWT token in /resolve

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#256]
As suggested by Calvin, he don't want his gateway to send (in nginx) `auth_request` to Authgear for every request.

The solution seems to be using, a combination of `auth_jwt` and `auth_request` as described in [nginx doc](http://nginx.org/en/docs/http/ngx_http_auth_jwt_module.html)

In that case, it seems we should have:
- A configuration to enable, return JWT token with the `/resolve` endpoint (by default or not? @louischan-oursky mentioned the way it works with JWS will leak some information in JWT header)
- A configuration to choose the TTL of the token (so how long it will need to resolve `/resolve` again?)
- Other JWT configuration like keys etc

**Comment by louischan-oursky** [comment]
The goal here is to avoid send subrequest to Authgear too often.

To solve this without modification to Authgear, one can add a cache between the gateway and Authgear. Technically, the cache read a specific cookie in `Cookie: ` and the value of `Authorization: ` to determine the cache key. The cache timeout should depend on the tolerance of stale information (e.g. user disabled, user verified).

The `auth_jwt` feature from Nginx is useful when the authentication server is already using JWT to encode the token. However, the token does not include information that requires real time query (e.g. user disabled, user verified). Therefore, I think we still need a `/resolve` endpoint to return up-to-date information.

Supporting JWT natively does not actually solve the problem if user information (e.g. user disabled, user verified) is crucial to the correctness of the application.

**Comment by chpapa** [comment]
1. But how does the cache layer works with gateways? Does that seem more engineering work / complicated for us to maintain another some daemon just for the cache? (Literally another /resolve endpoint); Because it seems JWT is the only standard that's widely adopted by different gateways? It also makes our user's deployment more complicated.

2. For user information like `disabled` or `verified`, that could be defined as private claims in JWT? Of course, the user of that feature need to be aware the date will be out-of-date for the TTL of the token.

**Comment by kiootic** [comment]
> But how does the cache layer works with gateways? Does that seem more engineering work / complicated for us to maintain another some daemon just for the cache? (Literally another /resolve endpoint); 

In my opinion, this cache layer is managed by the deployer of Authgear, so it is not maintained by us. This also ensure the deployer understand the implication of adding a cache layer: stale information may be used.

> Because it seems JWT is the only standard that's widely adopted by different gateways? It also makes our user's deployment more complicated.

Currently the `/resolve` endpoint resolves two kind of access credentials:
- IdP session: the session of a user directly logged in at Authgear.
- Access token: the token third-party client obtained when authorized by user through OAuth process.

OAuth access token can be a JWT, and is in pending standardization in a [RFC draft](https://tools.ietf.org/html/draft-ietf-oauth-access-token-jwt-07). We do not support this at the moment.

However, IdP sessions are long-term access credentials (days to months). Using JWT for IdP sessions is against best practice.

**Comment by chpapa** [comment]
> In my opinion, this cache layer is managed by the deployer of Authgear, so it is not maintained by us. This also ensure the deployer understand the implication of adding a cache layer: stale information may be used.

I don't think the user would like to do that, as those who choose to use a 3rd parties solution is to save his time on doing auth related stuff.

Plus coz most similar solutions seem to have it like auth0.com and okta, so either we come up with something better / easier to use? We can do an analysis of how it was done by others and how we could do it properly, instead of just jump to a conclusion say we are not going to solve it and users need to take care of it?

**Comment by chpapa** [comment]
> Using JWT for IdP sessions is against best practices

I understand this but seems some people take it as a compromise...

**Comment by kiootic** [comment]
> I don't think the user would like to do that, as those who choose to use a 3rd parties solution is to save his time on doing auth related stuff.

The original use-case is that the latency between Authgear and the gateway may be too high (e.g. inter-continent), and the distance between two components cannot be shorten. To most developers, the scenario should not be of concern. I don't think it is unreasonable to require extra work for a rather minority of users, provided a workaround is available.

> Plus coz most similar solutions seem to have it like auth0.com and okta, so either we come up with something better / easier to use? We can do an analysis of how it was done by others and how we could do it properly, instead of just jump to a conclusion say we are not going to solve it and users need to take care of it?

Auth0 can provide OAuth access token in JWT form, which as mentioned, is not supported at the moment. I do think this is nice-to-have, since it is pending to be standardized.

However, I don't think Auth0 provides an official way to access the IdP session token (i.e. the cookie created when user logged in at the Auth0 login page). I suppose most of SaaS platform would not provide this token too.

Since using JWT for long-term session is against best practice, and a workaround (a custom cache layer) is available, personally I would prefer to putting this issue on hold.

**Comment by chpapa** [comment]
> The original use-case is that the latency between Authgear and the gateway may be too high (e.g. inter-continent), and the distance between two components cannot be shorten. To most developers, the scenario should not be of concern. I don't think it is unreasonable to require extra work for a rather minority of users, provided a workaround is available.

Actually no, as spoken by Calvin and me, this is not just about latency, but also scalability issues. So even if it is not inter-continent, for economy stand-by many developer users might also not want to keep hitting the auth server on every request.

> Since using JWT for long-term session is against best practice, and a workaround (a custom cache layer) is available, personally I would prefer to putting this issue on hold.

I don't think we need to implement it now, but I'm worried if our final "proposed solutions" will be a big breaking change.

Can we at least agree and propose a solution/direction once we need to do that? So we know that will be our solution once we need it?

Is that basically we could simply replace the cookie string with JWT, although it is not the best practices? Or there are better options to do it?

**Comment by louischan-oursky** [comment]
Even we replace all tokens we issue with JWT, we still suffer from the fact that the JWT does not contain up-to-date information. The application gateway still need to call `/resolve` at some point. This is primarily a cache problem which is better to solved by a cache layer.

Some notes on switching to JWT, the cookie should be changed to short-live, which means we somehow need to write a new cookie containing a new JWT with user information at that moment. This would complicate the server calling `/resolve`, as this requires that server to propagate `Set-Cookie:` which it normally should not.

**Comment by kiootic** [comment]
> Actually no, as spoken by Calvin and me, this is not just about latency, but also scalability issues. So even if it is not inter-continent, for a performance standpoint many developer users might also not want to keep hitting the auth server on every request.

I believe that's not the case. nginx's `auth_request` config hits a server every request, and it is in common use. Using a proxy to validate OAuth access token is also a common approach.

> I don't think we need to implement it now, but I'm worried if our final "proposed solutions" will be a big breaking change.
> Can we at least agree and propose a solution/direction once we need to do that? So we know that will be our solution once we need it? (And I'm not convinced we can just tell people to "develop your workaround" when they need to decide using / paying for Authgear or not)

My suggested solution is to use OAuth third-party authentication instead of IdP first-party authentication, and use a ready-made access proxy product like [Oathkeeper](https://www.ory.sh/oathkeeper/docs/pipeline/authn/#configuration-5) or [oauth2-proxy](https://oauth2-proxy.github.io/oauth2-proxy/auth-configuration#openid-connect-provider) to perform authentication checks.

**Comment by chpapa** [comment]
> Even we replace all tokens we issue with JWT, we still suffer from the fact that the JWT does not contain up-to-date information. The application gateway still need to call /resolve at some point. This is primarily a cache problem which is better to solved by a cache layer.

@louischan-oursky This has been discussed and understood clearly when we discuss with Calvin (and above); it is okay to contain not up-to-date information, and it is okay for the application gateway to call /resolve at some point, as long as it is not EVERY request, but more like every 1 min or 5 mins. 

Plus using a cache layer would have the same problem too. So it seems a built-in solution is easier for end-user.

> Some notes on switching to JWT, the cookie should be changed to short-live, which means we somehow need to write a new cookie containing a new JWT with user information at that moment. This would complicate the server calling /resolve, as this requires that server to propagate Set-Cookie: which it normally should not.

@louischan-oursky Do you meant currently we set a random string as token in cookies, if we replace it with JWT, we will need to change it to short-live. May I know why? I thought JWT has an `exp` time that will expire itself, and force the gateway to resolve at `/resolve` again? And if we already using cookies now for the token, the server should be doing exactly the same thing?

 > I believe that's not the case. nginx's auth_request config hits a server every request, and it is in common use. Using a proxy to validate OAuth access token is also a common approach.

@kiootic Not saying it is believed or not, but in a production environment, I think it creates quite some challenge to us if we want nginx hit us with every request, despite the latency issue with the geo-distance problem, we need to ensure `/resolve` endpoint is very scalable and low latency. What does our `/resolve` endpoint is doing now? Is it totally stateless or it requires access to DB?

> My suggested solution is to use OAuth third-party authentication instead of IdP first-party authentication, and use a ready-made access proxy product like Oathkeeper or oauth2-proxy to perform authentication checks.

OAuth2-proxy looks simple and promising. Sounds like a good solution. But I think we would still want to:

- Make sure our /resolve endpoint is very scalable and hopefully mostly stateless (or with good caching itself in future if not), provide good latency.
- I think we will still run into it someday... maybe that meant at that point we will need to provide a pre-configured oauth2-proxy to users?

**Comment by louischan-oursky** [comment]
> Do you meant currently we set a random string as token in cookies, if we replace it with JWT, we will need to change it to short-live. May I know why? I thought JWT has an exp time that will expire itself, and force the gateway to resolve at /resolve again? And if we already using cookies now for the token, the server should be doing exactly the same thing?

We currently issue 3 kind of tokens.

## IDP session token

This token represents the session associated with the web UI. Our `resolve` endpoint can read it from `Cookie:` to resolve session. To make this happen, the application and Authgear must be in the same domain (i.e. sharing cookie).

This token currently is written once when the user perform authentication on the web UI. We do not have any mechanism to refresh it. It is an opaque string now.

## Refresh token

This token represents a session associated with a third party application. It is typically found in native application (e.g. React Native application, iOS application, etc). It can be used to obtain an access token. It is an opaque string. The `resolve` endpoint does **NOT** know this.

## Access token

This token represents a session associated with a third party application. In contrast to refresh token, it is short-live. Under default settings, its lifetime is 5 minutes. It is an opaque string now. Terry proposed to make this a JWT. The `resolve` endpoints can read it from `Authorization:`.

---

If we have made the access token a JWT with proper lifetime (e.g. the default 5 minutes), this problem is solved if the application never rely on the IDP session token. The gateway can rely on the information in the JWT as long as it is not expired yet. If the access token is going to expire, the SDK should have refreshed it. In this setup, no cache is required. Network calls are minimized.

If the application rely on the IDP session token, the remaining problem is to make the IDP session token behave similar to the access token, which is short-live and can somehow be refreshed. I am not sure if `/resolve` endpoint should have side-effects of refreshing the token and include `Set-Cookie:` in the response. This also why Terry suggested solution is to use OAuth third-party authentication. We just need to make the access token JWT, which is going to be the standard anyway.

**Comment by louischan-oursky** [comment]
Closing in flavor of https://github.com/authgear/authgear-server/issues/318
