### ISSUE TITLE
[OTP] Configurable Cooldown period

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2781]
## Requirement

- The current cooldown is set to 60s. Make it configurable per project so that user can choose 60s or 120s

### AuthUI

![Image](https://user-images.githubusercontent.com/15207470/211144709-81598628-df9d-4873-9d8b-4dfdf0d5d46e.png)

### Portal

![Image](https://user-images.githubusercontent.com/15207470/211144775-03c88402-1802-4a75-a7f1-062052a992fc.png)

Add "Cooldown duration before resending OTP" and a dropdown of 60 seconds / 120 seconds

**Comment by louischan-oursky** [comment]
## Add the new config `verification.code_resend_cooldown_reconds`

Since we have `verification.code_expiry_seconds`, we are going to add `verification.code_resend_cooldown_reconds`. The JSON schema of it should be

```
{
  "type": "integer",
  "enum": [60, 120]
}
```

In Go, it should be a `DurationSeconds`. Implement SetDefaults() such that if it is zero, the default value is 60.

## Use `verification.code_resend_cooldown_reconds` for cooldown

We now have AntiSpamSendVerificationCodeBucket and AntiSpamSendOOBCodeBucket, let's unify them into AntiSpamOTPCodeBucket. Use `otp-code:%s` for the key.

Now that the bucket depends on the config, it is reasonable to use dependency injection to get the bucket. Since wire injects by type, we cannot provide `ratelimit.Bucket` directly. Doing so means we can ever inject this and only this bucket. It is very simple to circumvent this limitation. We introduce a new type to contain a ratelimit.Bucket.

```golang
type OTPCodeBucket {
  Bucket ratelimit.Bucket
}

func ProvideOTPCodeBucket(cfg *config.VerificationConfig) OTPCodeBucket {
  // use cfg to construct the bucket
}

var DependencySet = wire.NewSet(
  // other deps
  ProvideOTPCodeBucket,
)
```
