### ISSUE TITLE
Support use cases where 2FA is used as user attributes

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#2811]
## Use case 

The some use cases, during signup phone number and email are collected. It's set up by using phone as "Identity" and email as secondary auth (2FA).

In the current design, while phone number is available, they cannot get the email immediately from the SDK (UserInfo endpoint). And they must get it from the Admin API through the backend.

## Discussion

- The separation between user profile and 2FA authenticators was a design decision to prevent users from misusing 2FA for purpose besides authentication. See: https://www.ftc.gov/business-guidance/blog/2022/05/twitter-pay-150-million-penalty-allegedly-breaking-its-privacy-promises-again

## Solution

Make it easy to copy the claims from authenticators and store it in custom attributes using event hooks
The attribute and claims in 2FA must not become out-of-sync.

Todo:

- [ ] #2842
     - Create script to ensure no one is using `user.session.jwt.pre_create`
     - Rename event
- [ ] #2843
- [ ] https://github.com/authgear/authgear-server/issues/2804
- [ ] https://github.com/authgear/authgear-server/issues/2810
- [x] https://github.com/authgear/authgear-server/issues/2806

Not completely related but a likely requirement that comes with the above use case: 
- [ ] https://github.com/authgear/authgear-server/issues/2807

**Comment by carmenlau** [comment]
## Background

During the discussion, we think that the authenticator is the implementation detail. Most of the Authgear users should not care when a 2FA is setup, since they delegate the authentication process to Authgear already. So we don't want to add those authenticator related events. Instead, we have the following proposal

### Support obtaining the 2FA email from the user info

- Add new blocking event `user.profile.enrich_userinfo` (TBC: event name), the developer can use this hook to alter the response of userinfo endpoint.
    - The client can implement this hook, call the admin api to obtain the 2FA email and add it into the userinfo response.

### Support obtaining the 2FA email from JWT token

- Use the existing event `user.session.jwt.pre_create`.
    - The client can implement this hook, call the admin api to obtain the 2FA email and add it into the jwt payload.

### Support 2FA email unique

Unless Authgear supports unique 2FA email, we cannot have a strong guarantee for email uniqueness. Given that we don't have a plan to support unique 2FA email in Authgear, we have the following proposal:

- Support new blocking event `user.check_email_address` (TBC: event name). For all the email-related features (e.g. adding/updating email login id, adding/updating email otp or magic link, ...etc.), this blocking event will be called.
    - The client can implement this hook, call the admin api to search if another user is using this email. Abort the event if the email is occupied.
    - Pros
        - This event is genric, other Authgear users can use this event to implement their own email address checking logic.
    - Cons
        - If 2 signup/update happens at the same time, and they are using the same email. There will be duplicated emails.

Todo:

- Support new blocking event to mutate retrieved usrinfo
- Support new blocking event to check email address. To keep it simple the event will only provide email address. No user, authenticator type or other information will be provided in the event.
- Make deno hook access admin api easily. e.g. jwt in deno env var
- Update admin API to support searching user by email (including 2FA email). The existing user search API only supports searching users by email identities and standard attributes.
