### ISSUE TITLE
Web UI theming

### ISSUE THREAD

**Issue by kiootic** [authgear/authgear-server#291]
- [Update web UI to match latest design](https://github.com/authgear/authgear-server/issues/864)
- [Make web UI theme-aware](https://github.com/authgear/authgear-server/issues/864)
- [Store theme in app FS CSS file with special comment blocks surrounding the theme CSS declarations](https://github.com/authgear/authgear-server/pull/908)
- Add preview on theme change

---

#### Original description

Since we're using Fluent UI design in settings page, which is a plain web app (not SPA), we may want to look into using [Fabric Core](https://developer.microsoft.com/en-us/fluentui#/get-started#fabric-core), the official CSS-only framework for Fluent UI design.

**Comment by louischan-oursky** [comment]
Fabric Core is basically this CSS file https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.css

It basically includes the following things

1. [A Grid system](https://developer.microsoft.com/en-us/fluentui#/styles/web/layout#grid). But the doc suggests that you can use CSS grid instead. We are using CSS grid already
2. A number of class names that form a theme. This may be not be applicable to us, since we are still not sure about how are we going to do theming.
3. A number of class names for using fluent UI icons. But we are actually using font-awesome for most icons.
4. A number of class names for controlling font size. I guess font size should be part of the theme?
5. Some utility class names, such as clearfix.

So adding Fabric Core may not be very useful to us. Thoughts? @carmenlau @kiootic

**Comment by kiootic** [comment]
It seems the component styles are moved to `office-ui-fabric-js` (which is deprecated in favor of the new react-based library) at v3.0.0. I suppose we can hand-roll the component styles ourselves using SCSS?

**Comment by louischan-oursky** [comment]
How [Fabric UI Theme Designer] works?

The code responsible for generating a theme has the following parts

1. https://github.com/microsoft/fluentui/blob/master/packages/react-internal/src/components/ThemeGenerator/ThemeRulesStandard.ts
2. https://github.com/microsoft/fluentui/blob/master/packages/react-internal/src/components/ThemeGenerator/ThemeGenerator.ts
3. https://github.com/microsoft/fluentui/blob/master/packages/react-internal/src/utilities/color/shades.ts
4. https://github.com/microsoft/fluentui/blob/master/packages/theme/src/utilities/makeSemanticColors.ts

Basically the input is Primary Color, Text Color and Background Color. And the they define a shade of 9 levels (no shade, and shade 1 to 8) to derive the shades of a given color. This would give a color palette. From the color palette, they have `makeSemanticColors` to convert the color palette to a semantic palette. Finally each component define its styling by referring to a color in the semantic palette.

Since the assignment of semantic colors to component styling are buried in the source code of Fluent UI, it is hard for us to follow them strictly. I guess we could borrow their idea of having some basic colors (like Primary Color, Text Color and Background Color) and apply shade to derive our own color palette. And then we should formally define what components do we have and the semantic palette.

**Comment by louischan-oursky** [comment]
We will a runtime in the portal to generate the palette. The generated palette will be saved in the app CSS. We need to be able to parse CSS, extract the palette and manipulate it.

**Comment by mr9dollars** [comment]
https://www.figma.com/file/msiE4O5imHONAG5EjhZeiZ?node-id=1840:4096#61663356
Design for UI settings ready
