### ISSUE TITLE
Confusion in user id / node id in portal & admin api

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3095]
There are two type of ids in authgear.
Node id: `VXNlcjo2YWJiOTZjNy0zMWY4LTRmYWQtODJjZC1mMDM3MGRhZjhlMTU`
UUID: `6abb96c7-31f8-4fad-82cd-f0370daf8e15`

In admin api / urls, it seems we are always using node id
In portal displayed screens, it seems we are always using uuid

I think it is a bit confusing and not sure which one is the id we should display to the user.

Also, I think we might want a field in portal to display & allow copying the user id.

**Comment by chpapa** [comment]
Which url have the node id? It should be removed as previous discussion was node id is solely used in graphQL. I think we should remove it asap (and any other usage of node id instead of user id in place other than graphql API)

ref #1970

If it confused even our own developers, maybe should seriously consider obsolete / remove it now.

**Comment by fungc-io** [comment]
To be followed up in #1970 and #3117 
Marking this issue as closed.
