### ISSUE TITLE
[Biometric] Multiple biometric logins will be created for the same device if user enables it for multiple times

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3167]
## Background
- Environment: Staging
- Testing app: iOS TestFlight - Flutter / RN / Xamarin / Native
- Build: 1.0.0 (1687258327)
- Device: iPhone SE 2 (iOS 16.4.1 (a))
- Testing app: smart-swallow-805 - https://smart-swallow-805.authgear-staging.com
- Testing user: joyz@oursky.com

## Description
When user uses the "Enable Biometric" function for multiple times, even though it is the same user on the same device, it will create multiple biometric login items in the user settings.

Not sure if it is bug or not, report as UX first as I initially expect that it should either be the same biometric login item or overwrite the old one.

## App configuration (test sample)
1. Anonymous enabled
2. Mobile or email login
3. Password login
4. Passkey enabled
5. Biometrc enabled
6. SSO enabled

## Steps to reproduce
1. Authenticate and Sign up
2. Enable biometrc
3. Check user settings, see 1 biometric item for this device
4. Logout
5. Authenticate and Login to the same account
7. Enable biometric again
8. Check user settings, see 2 biometric items for this device

## Video

https://github.com/authgear/authgear-server/assets/12539486/2d51a36e-ef82-4a1e-92ff-b0e0844f07b8

**Comment by fungc-io** [comment]
This shuold be a demo app problem, it should alwasy check if biometric is already enabled.

**Comment by tung2744** [comment]
@louischan-oursky Do you think we should handle this in sdk? Say if there is already a biometric key id, we should throw an error?

**Comment by louischan-oursky** [comment]
> Do you think we should handle this in sdk? Say if there is already a biometric key id, we should throw an error?

Yes. But we also need to disable the enable button in the demo app.

**Comment by tung2744** [comment]
@fungc-io @louischan-oursky After looking into this issue in detail, I think this is not a demo app problem.
This problem actually happens after the user logged out and re-login. Therefore it makes sense that the user can re-enable biometric. I think the problem here is:
1. Should we remove the corresponding biometric key from authgear on user revoking his session?
2. If no, should we deduplicated the public key in authgear server when user enables biometric with a key we already know?

**Comment by fungc-io** [comment]
This behavior is expected.
It's extremely unlikely for a app that uses biometric to allow login to another user without logging out the current user.

If authenticate is triggered again on the app and an user completed the login, the existing biometric keys are removed from the device locally.
The biometric key record is not removed from the server, and creating a new one will not overwrite the old keys because it's not possible to determine it's from the exact same device.

**Comment by fungc-io** [comment]
In our current design,
We expect after login with non-biometric methods (e.g. password) , the app should ask the user to enable biometric again
