### ISSUE TITLE
Update user detail connected identities screen + add identity screens

### ISSUE THREAD

**Issue by axolotl0212** [authgear/authgear-server#331]
- [x] add verify / unverify button (force verify, directly change state, not performing verification)
- [x] handle item verified / unverified state
- [x] update item description to include verified
- [x] verify only exist in phone / email

- [x] add identity context menu
- [x] email, phone, username link to corresponding screen
- [x] setup screen for add email, phone, username

**Comment by kiootic** [comment]
A point on the add username page in portal (`authgear-fluent-user-details-addusername`):

Suppose the user currently only have a phone, and login through passwordless SMS (i.e. one phone login ID identity & one primary OOB-OTP authenticator). When the admin adds a username, a new password should be entered by admin/generated automatically, since otherwise the user cannot login using the username.

cc @louischan-oursky @keithtkl

**Comment by keithtkl** [comment]
@kiootic are you suggesting the screen `authgear-fluent-user-details-addusername` should have both username and password fields in the case that you mentioned?

cc @louischan-oursky

**Comment by louischan-oursky** [comment]
I suggest we always show a password field under the primary text field (be it email, username or phone). If password is determined to be unnecessary, disable the password field with a description telling the admin that this user has already had a password.
