### ISSUE TITLE
Unable to reauth when the project configs changed from password to passwordless

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3469]
In https://github.com/authgear/authgear-server/issues/3402 ,
We solved the problem where the config is changed from password to passwordless after the user is created. i.e. the User signed up with pw can now login with passwordless magically.

However we missed the case for Reauth.

## Step to Reproduce

- Project support only PW Signup/login
- User signed up with pw
- User logged in with pw
- Project config changed to passwordless
- User tries to re-auth
- Sees error message: "No authenticators available"

The reverse case also holds true (Passwordless changed to password)

## Screenshot

![Image](https://github.com/authgear/authgear-server/assets/15207470/03f528a9-df03-4801-a1c1-0b8379a66641)

**Comment by louischan-oursky** [comment]
1. From the screenshot of https://github.com/authgear/authgear-server/pull/3435, we see that we do not allow the end-user to forgot password during reauthentication. So it follows that we show the error message telling the end-user that they do not have any usable authenticators.
2. If we want to improve this case, we need to
  - Support forgot password during reauthentication
  - That implies we need to support restart of a original flow.
  - Make forgot password success page able to navigate back to the original flow.

**Comment by louischan-oursky** [comment]
1. Support password -> passwordless
2. Return OAuth error with `error=TBC`.

**Comment by louischan-oursky** [comment]
Currently we do not support aborting an authentication flow.

1. The `finish_redirect_uri` (which is `/oauth2/content`) always expect authentication info. We do not support redirect back to `/oauth2/content` with an error generated by the client of authentication flow API.
2. The `finish_redirect_uri` is only present when the flow finishes. The client never know what URI they should use to abort the flow.

For now, I will update the error screen so that it is not shown like an internal error. But there will be no buttons. The end-user has to cancel the flow themselves, and contact customer support. If the end-user is missing a password, the customer support can ask the end-user to sign out, and use the forgot password flow to reset the password.

**Comment by fungc-io** [comment]
Created follow up issue: https://github.com/authgear/authgear-server/issues/3477
