### ISSUE TITLE
[Portal, Localization] Blank screen if switch to a newly added language before save

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3627]
## Environment
- Environment: Staging
- App: Any
- Browser: Chrome on Macbook Pro

## Description
If user add a localization on portal, and before save, switch to that language on the dropdown, it throws error and shows a blank screen.

## Steps to reproduce
1. Login to admin portal
2. Go to "Localization"
3. Click on the gear icon to add a language, e.g. Chinese (Traditional)
4. Set it as default
5. On the dropdown besides, switch to that newly added language
6. See blank screen (with error in console log)

## Expected behavior
Should either show the display of changed language, or do not let user choose the language before save.

## Screenshots
<img width="1472" alt="Screenshot 2024-01-16 at 5 08 55 PM" src="https://github.com/authgear/authgear-server/assets/12539486/233fce86-3804-4426-b5e7-f173b763ed71">

https://github.com/authgear/authgear-server/assets/12539486/540b9970-2043-436c-a34b-c9962e130de4

**Comment by fungc-io** [comment]
Hi @newman
I think the UX is a bit weird now we don't show the newly added language before save.

This is a design flaw that need to be fixed by changing how a language is added. Without changing the design much now, how about showing the newly added lang as a disabled option.

e.g. After I added "Arabic" 

<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/915695c1-cd0b-4757-9f95-fedf73dcf5e5/0e54f65b-4283-436b-95dc-a36d954833e1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi85MTU2OTVjMS1jZDBiLTQ3NTctOWY5NS1mZWRmNzNkY2Y1ZTUvMGU1NGY2NWItNDI4My00MzZiLTk1ZGMtYTM2ZDk1NDgzM2UxIiwiaWF0IjoxNzA5OTE1ODQyLCJleHAiOjMzMjgwNDc1ODQyfQ.ft_F4Armqeu_rZsShsYTCZFTt41QUD325val-qrgpyg " alt="image.png" width="392" height="172" />

And provide help text under the selection box to remind the user to save the changes

<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/f3f6c198-e65f-4e8e-b036-5cc8ac19e50d/2b68c9dd-e506-4c9d-ab89-b2e51308f6fd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi9mM2Y2YzE5OC1lNjVmLTRlOGUtYjAzNi01Y2M4YWMxOWU1MGQvMmI2OGM5ZGQtZTUwNi00YzlkLWFiODktYjJlNTEzMDhmNmZkIiwiaWF0IjoxNzA5OTE1ODQyLCJleHAiOjMzMjgwNDc1ODQyfQ.sHG3HaOxY0Gib9VqltIGJgnvmB70udA2bSpQx9q9oNA " alt="image.png" width="428" height="147" />

**Comment by fungc-io** [comment]
I've moved this to todo.

**Comment by louischan-oursky** [comment]
Need some clarification on the 3rd case.

Originally:
English (default)
Hong Kong Chinese

Edited:
Hong Kong Chinese
English (Removed)
China Chinese (default)

At this point, Hong Kong Chinese is still selectable, so we will not prompt the dialog, right?

**Comment by fungc-io** [comment]
@louischan-oursky ,
yes, with the Chinese (HK) selected, and 2 other disabled

**Comment by fungc-io** [comment]
@newman there are 2 design missing in my testing.

1. It was quite subtle in the figjam, i should have marked it clearer, the disabled option in the dropdown should have a lighter font color. please refer to this grey color here:

   <img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/67d0b0db-2da3-4655-9c8b-2c317c7af24d/42931328-0822-4049-825f-ceaf376094e7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi82N2QwYjBkYi0yZGEzLTQ2NTUtOWM4Yi0yYzMxN2M3YWYyNGQvNDI5MzEzMjgtMDgyMi00MDQ5LTgyNWYtY2VhZjM3NjA5NGU3IiwiaWF0IjoxNzExMzA3MzY3LCJleHAiOjMzMjgxODY3MzY3fQ.MwLG12IV67KXj6Que9HIlIBn16D1_DnLEebZeFDVc8c " alt="image.png" width="937" height="801" />
2. In the last case for adding a language and removing the original default, the dialog should be pop up before I press save.
   1. Original: 
      1. English-Default
   2. Change to:
      1. Add Chinese, set as default
      2. Remove English
   3. When I press Apply, the dialog should be shown and the page is refreshed.
   4. The current implement on staging, after i press Apply, the UI will show the English translation while the dropdown on the top right is showing "Chinese", which is not ideal.

**Comment by IniZio** [comment]
@fungc-io 

For 2, I think it might be confusing if the Apply behaves that differently based on number of languages though?

**Comment by fungc-io** [comment]
But in this case, there should be nothing selectable in the dropdown after "Apply", because the default is being removed and the new language is not saved yet.
