### ISSUE TITLE
Invalid password format error should precede password not match error

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3733]
When the upper field is invalid, it should indicate the error above.
When the upper field is valid, then check for the 2nd field matching

![Image](https://github.com/authgear/authgear-server/assets/15207470/1d1cd867-ffa8-4e27-a0b5-3ba3b2b0e994)

**Comment by tung2744** [comment]
@fungc-io After discussed with louis, we think it doesn't worth to modify authflow api for this case.
We propose the following changes:

1. When user blur the first text field, frontend will check the password policies that can be checked in frontend. If any policy is violated, the first field will become red. No error message will appear.
2. When user blur the second field, frontend will check if the two fields match. If they don't match, the second field will become red, and show "The re-typed password does not match...".
3. When user submit the form, backend will still check the second field matches the first field first, then check the password policy (Same as current behavior). Note that in step 1, not all policies can be checked in frontend (such as password history is not checkable in frontend), so the problem described in this issue is still reproducible, but we think the previous 2 steps should reduce the chance of user hitting this problem.

cc @louischan-oursky @Ngkaokis
