### ISSUE TITLE
Remove the "Clear" "x" button in the country search box

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3847]
It's suggested to remove the "Clear" button in the search box
Because there are a lot of "X" cluster at the top-right on the screen

![Image](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/3c17efff-45ac-4975-a264-810d0fe36589/fabdcd57-a86d-45f7-8c60-beb6e0db1a80?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi8zYzE3ZWZmZi00NWFjLTQ5NzUtYTI2NC04MTBkMGZlMzY1ODkvZmFiZGNkNTctYTg2ZC00NWY3LThjNjAtYmViNmUwZGIxYTgwIiwiaWF0IjoxNzA5MTkwMTEyLCJleHAiOjMzMjc5NzUwMTEyfQ.9cUAq6-NDJMsEH2WiYUMJmKtJQVNmZn4OG_oZQfQ4do)

**Comment by IniZio** [comment]
I assume we can still keep the clear button on tablet and above screen sizes? @arvinho any concern 🙏 ?

**Comment by fungc-io** [comment]
ok thanks

**Comment by fungc-io** [comment]
@arvinhoux 
It will show if the user is using WebkitWebview UI, which is introduced recently.

> This was considered due to the possibility that the Android system might not have a cancel button, hence the addition of the close button.

How about change it to "Cancel"?

Like this:

![image](https://github.com/authgear/authgear-server/assets/15207470/248589d2-8c2e-43b6-bbb2-7f22a1f50a52)

**Comment by arvinhoux** [comment]
Based on my understanding, Android typically doesn't use a "cancel" button, and instead, it's more common to use the "close" icon button. This is also the common practice within Material Design components.

<img width="311" alt="image" src="https://github.com/authgear/authgear-server/assets/149644368/1dfcb7c4-f227-4142-9bd7-022febbb8c95">

**Comment by fungc-io** [comment]
In the AuthUI, we will keep the design universal for iOS and Android.

**Comment by arvinhoux** [comment]
Yes, so I would tend to prefer the universal "Close" instead of "Cancel" in this case.

Additionally, I haven't encountered WebkitWebview UI before. If this is a new approach, I would need to be informed to avoid affecting the existing design. Alternatively, if there are links to usage guidelines, please provide them for me to refer to.

**Comment by arvinhoux** [comment]
In this scenario, if there are top action buttons, I would lean towards using "Close" instead of having both "Back" and "Close". However, I would need a clearer understanding of the actual adjustments made to make a more informed decision on this matter.

Then, the "Close" button on the right side of the search bar might also be unnecessary.

**Comment by fungc-io** [comment]
btw let's move this discussion in [DES-7](https://linear.app/authgear/issue/DES-7)

This issue is about the clear button in the search box, not the close button
