### ISSUE TITLE
Technical Planning for setup product analytics

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#4113]

**Comment by louischan-oursky** [comment]
* Backend
  * Study whether we can use Deno hook to integrate with Posthog. (5p)
    * Test whether we can import the Posthog Node.js SDK in a Deno hook
    * Test whether we can capture a Posthog event in a Deno hook
  * signedUp
    * Listen `user.created` in the Deno hook and capture a Posthog event. (1p)
  * survey.completed
    * Nothing needs to be done at the moment (0p)
  * createdProject
    * Listen `project.app.created` in the Deno hook and capture a Posthog event. (1p)
  * createdApplication
    * Listen `project.app.updated` in the Deno hook
    * Detect an application is created. (1p)
    * Capture a Posthog event. (1p)
  * acceptedInvite
    * Listen `project.collaborator.invitation.accepted` in the Deno hook and capture a Posthog event. (1p)
* Frontend
  * Configure GTM to integrate with Posthog. (5p)
  * Capture events according to the list. (5p)

**Comment by louischan-oursky** [comment]
I studied Posthog group(1), and the proposed use case. I think Posthog group is not a tool for the use case.

1. All 5 metrics you propose is a number, like MAU, user count. But the key of a Posthog group is a string(2).
2. Each Posthog project can have at most 5 Posthog groups. The intended usage of Posthog group is to let you to associate a event with a group, so that you can perform aggregation on the group later. Aggregating numerical values is very rare.

(1): https://posthog.com/docs/product-analytics/group-analytics
(2): https://github.com/PostHog/posthog-js/blob/main/src/posthog-core.ts#L1298

I guess we need to re-think the use case.

**Comment by chpapa** [comment]
@louischan <br><br>I'm not sure about the exact details here. But can't help but notice that you wrote "each posthog project can have at most 5 posthog groups" is definitely wrong. It should be "5 group types", not 5 groups.

And MAU, user count, according to posthog structure, should be in group. Becoz in Authgear, MAU / user count etc does not belongs to user. They should be belongs to a Project, and Project should be Group in Posthog.
