### ISSUE TITLE
Some validation error does not contain location

### ISSUE THREAD

**Issue by axolotl0212** [authgear/authgear-server#550]
For example, in `createIdentity`, email and username has validation for its format. If falied, the error `reason = ValidationFailed -> kind = "format"` is thrown with empty location

Portal cannot use JSON pointer to distinguish between username, email, phone and password field (password might be required for username identity)

Related portal pages:
- Add username
- Add email
- Add user

**Comment by kiootic** [comment]
This issue is rather complicated: the main cause is the error went through many layers, therefore we don't have enough context to re-construct an accurate error.

The login ID goes through the layers like this:
- Login ID is accepted through GraphQL admin API layer, and translated into interaction input
- Interaction input is goes through the interaction mechanism, and translated into a login ID identity
- The login ID identity goes through login ID identity specific validator (`loginid.Checker`), which reject the login ID based on format.
- The error is propagated up back to GraphQL layer, and the API error is extracted and presented to API consumer.

There are two main problems to solve here:
- How to retain correlation between GraphQL input and interaction input fields.
- How to map generic errors (e.g. currently `Invalid: ValidationFailed`) into more specific errors (e.g. `Invalid: InvalidLoginID `) using additional context.
