### ISSUE TITLE
Investigate why authorization request is sometimes sent twice

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#594]

**Comment by kiootic** [comment]
The root cause is we use XHR to handle form submission.

To maintain a user-friendly browser history stack, we replace native form submission with custom XHR logic when JS is available. It first post the form to the action endpoint, then navigate the browser to the final redirect URL if success.

When OAuth authorize endpoint is used, the flow goes like this:
1. User press submit button in a page. (e.g. `/enter_password`)
2. Client side JS use XHR to submit the form.
3. Server web UI module ends the interaction and redirect to OAuth authorize endpoint.
4. OAuth authorize endpoint generates the code and write a HTML snippet to redirect to OAuth redirect_uri. (This is needed to account for quirks of some platforms)
5. The XHR completes, with the OAuth authorize endpoint as the final URL.
6. The client JS redirect the browser to the final URL (i.e. the OAuth authorize endpoint)
7. The authorize endpoint generates the code again.

To solve this problem, there is two main ways:
- Prevent the second request
- Ensure the second request would not generate code again

We suppose the second way would not be satifactory, the code is still being transmitted unnecessarily on wire.

Therefore, to prevent the second request, we suggest to modify the existing XHR form submission mechanism to replace the page HTML directly, instead of redirecting user.
