### ISSUE TITLE
Include account ID for setting page request for iOS/Web/Android SDK and docs.

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#761]
It is impossible to ensure opening settings page would always not require user login as long as the user is logged in the app, since OAuth token lifetime is not the same as IdP session lifetime.

However, it would also be perceived as bugs for users if it doesn't.

A solution is to:

1. Setting page accepts a parameter for some sort of account ID, which will prompt the user to re-login at the specific account once there's no valid session.
2. Update our iOS/Android/Web SDK, and documentations, to include that account ID in all setting page requests.

**Comment by louischan-oursky** [comment]
A different approach to this issue is to do not rely on the IdP session to access the settings page. The application can use the refresh token to exchange a new token to the settings page. This new token is ephemeral. An advantage of this approach is that the lifetime of the refresh token matches the period where the user can access the settings page. However, this also means anyone with the refresh token can access the settings page, notably the OAuth client can do it. Therefore in this approach the OAuth client is privileged.

**Comment by chpapa** [comment]
@louischan-oursky Sounds interesting.

> However, this also means anyone with the refresh token can access the settings page, notably the OAuth client can do it

Under what circumstances would user with refresh token shouldn't have access to settings page? Or this is more hypothetical that "in future, we may have a Client ID that should not have the scope/access to setting page"?

> A different approach to this issue is to do not rely on the IdP session to access the settings page

Practically, it seems we need both? It is still possible that for example, SSR web application are suppose to use IdP session to access the setting page. So we need both?

**Comment by kiootic** [comment]
> Under what circumstances would user with refresh token shouldn't have access to settings page? Or this is more hypothetical that "in future, we may have a Client ID that should not have the scope/access to setting page"?

Under OAuth protocol, the bearer of refresh token/access token only have *delegated* access to API by user; most OAuth-based API does not allow privileged operations to be performed using access tokens (e.g. cannot change Google password through its OAuth API). That's why we'd need to introduce a concept of 'privileged client'/'first-party client' to be consistent with design of OAuth.

**Comment by chpapa** [comment]
> Under OAuth protocol, the bearer of refresh token/access token only have delegated access to API by user; most OAuth-based API does not allow privileged operations to be performed using access tokens (e.g. cannot change Google password through its OAuth API). That's why we'd need to introduce a concept of 'privileged client'/'first-party client' to be consistent with design of OAuth.

icic, oh right, how will it actually works? Like a special attribute with the Client ID that tokens generated by this Client ID is "privileged client/first-party client"?

**Comment by kiootic** [comment]
I suppose the concrete flow is like this:
1. App open settings page using client SDK
2. Client SDK redirect to OAuth authorize page with specific parameters, and `redirect_uri` set to settings page URL:
    - Configured as third-party client: include ID token as `login_hint` parameter & set `prompt=none`.
    - Configured as first-party client: include (TBD) token as (TBD) parameter (ref #737, #796)
3. OAuth authorize page ensure a valid IdP session exists before redirecting to `redirect_uri` (i.e. settings page):
    - If ID token presents in `login_hint` (i.e. third-party client):
        - If valid IdP session presents: redirect directly, even if does not match ID token.
        - If no valid IdP session: perform authentication, with identity step pre-selected using the ID token.
    - If (TBD) token presents (i.e. first-party client):
        - If valid IdP session presents: redirect directly, ignoring the (TBD) token.
        - If no valid IdP session: transform the token into IdP session and set corresponding session cookie, and redirect directly.

**Comment by chpapa** [comment]
@kiootic Do you think it is okay and better, for reducing the latency (reduce one redirect), to go step 3 first, and if failed, go back to step 2 by Client SDK's logic?

**Comment by kiootic** [comment]
> go step 3 first, and if failed, go back to step 2 by Client SDK's logic?

The settings page will redirect to authentication page if no valid session exists, therefore we cannot insert client SDK logic in the middle of redirection.

**Comment by kiootic** [comment]
Additional notes:
For third-party clients, we should use OIDC `id_token_hint` parameter. Therefore, we should include enough information in ID token to enable 'select identity' step to be performed without user interaction.

We have three identity types at the moment:
- For login ID identities, we should include email/username/phone in ID token, so the corresponding login ID identity can be selected from the ID token. This requires #260.
- For OAuth identities, we should include the OAuth provider alias (or ID?), so we can redirect user to specific OAuth provider directly to perform authentication.
- For anonymous identities, we currently use `login_hint` with a signed JWT as authentication mechanism, I suppose we can keep this intact.

**Comment by kiootic** [comment]
Additional notes:

For first-party client mobile apps, we may want to provide a one-time-use token to 'transfer' the session from the native app to web UI (avoid putting reusable access token directly in URL).

Currently access tokens are bound to either a refresh token (i.e. `OfflineGrant` when refresh token is requested through OAuth protocol), or a IdP session (when refresh token is not requested); the access token becomes invalid if the bound refresh token/IdP session became invalid.

Therefore, we may introduce a new endpoint, so that first-party clients may obtain a one-time-use *session token* using an access token bound to a IdP session. Then, native app may pass this *session token* to OAuth authorize endpoint as `login_hint` parameter.

After validating the *session token*, the authorization process would:
1. Regenerate session cookie value of the bound IdP session, in order to invalidate other active session cookies.
2. Set the session cookie using the bound IdP session, and finish the authorization process.

**Comment by louischan-oursky** [comment]
Could Terry help consolidate the things we have discussed and write a spec?

**Comment by kiootic** [comment]
After discussion with @louischan-oursky & @carmenlau, we will handle first-party case first, since third-party case would depends on #260 and specification of OIDC profile consent.
