### ISSUE TITLE
[App, Forgot password, UX] Can proceed the reset password flow with another user's email?

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#783]
## Background:
- Device / Browser (OS version): Chrome on Mac OS 
- Build: staging 24-22-2020
- Remark: Reported by tester

## Description:
I am using account aa (username : aa , with no email) to reset PW. 
But I can use {Email B} to reset "user aa" account ( which is disabled and this email is for another user ). 

Ps: The email {Email B} have already bound to another user.

1. Go to https://ourskyqa.authgear-staging.com
2. Login by username and click "Next"
3. Click "Forgot Password?"
4. Input a valid email (this email have bound to another user.) and click "Next"
5. You will see a message "Request received If you have an account, please follow the instruction sent to {Email B} to reset your password "
6. I can receive the email to reset password.  

## Expected result:
User should not allow using another user's email to proceed the reset password flow.
Or, the reset password flow may better revised.

## Screenshot:
![Screenshot_2020-11-24_at_2.55.57_PM](https://gitlab.com/skytester/authgear-server/uploads/5e8d16050a4367b859f9719174484028/Screenshot_2020-11-24_at_2.55.57_PM.png)

**Comment by louischan-oursky** [comment]
Actually the forgot password flow is entirely separate from the authentication flow. So conceptually when you enter the forgot password page, the authentication flow is interrupted. The email you entered is for the forgot password flow, not related to the username you entered in the authentication flow.

**Comment by carmenlau** [comment]
To avoid confusion, we will pre-fill the forgot password form when user click the forgot password link in enter password page. That means if user input email in the first step and click the forgot password link in the enter password page, the inputted email will be shown on the forgot password page, so user will know they are resetting password for the same account.

**Comment by chpapa** [comment]
Actually I think this issue have a lower priority (but if Carmen looked at it already maybe as well finish this :) 

BTW, is it better to "prefill" the forgot password form with the email address, or better if we "enforce" the flow is with the email address? (Just asking question, haven't given it much thought myself)

**Comment by joyzoursky** [comment]
@chpapa @louischan-oursky @carmenlau I think it is not very good to "prefill" the password, as it will leak user email info if someone randomly input some username retrieve others' email.

Instead, I think it is better to clarify more one this point from the UI:

> forgot password flow is entirely separate from the authentication flow

A suggestion will be revising the "Back" button instead, to go back to the landing page instead of the previous input password page, so it will not confuse user that he/she is resetting the password for the username account, but better clarify that it is a separate flow.

![Screenshot 2020-12-08 at 4 42 18 PM](https://user-images.githubusercontent.com/12539486/101460651-d788fa00-3974-11eb-8326-17511dd8d9ab.png)

**Comment by chpapa** [comment]
>  I think it is not very good to "prefill" the password, as it will leak user email info if someone randomly input some username to retrieve others' email.

I don't think it would happen, only if you entered the email address, the forgot password will fill in the email address for you.

> A suggestion will be revising the "Back" button instead, to go back to the landing page instead of the previous input password page, so it will not confuse user that he/she is resetting the password for the username account, but better clarify that it is a separate flow.

I think it might help a bit...

**Comment by joyzoursky** [comment]
@chpapa @carmenlau In that case the handling for "prefill" email is not solving what the original issue mentioned.

As the issue is about user:

1. Fill in **username** (not email)
2. Click Next
3. Click Forgot password
4. Fill in others email
5. Reset password for others (not the account in Step 1)

**Comment by carmenlau** [comment]
@chpapa @joyzoursky Sorry I used a wrong word "per-fill" 🙈. Actually we planned to do "enforce". 

1. User fill in email 
1. Click Next go to enter password page
1. Click Forgot password
1. User will see the forgot password page with the email which he inputted in step 1. Not editable. 
1. User can click to request forgot password

For the username case, since we don't support reset password if user signup with username for now. So we removed the forgot password link in enter password page if user filled in username. So only phone and email will have the forgot password link.

**Comment by chpapa** [comment]
@joyzoursky 

I still don't see why the issue described below is a problem.

> Fill in username (not email)
> Click Next
> Click Forgot password
> Fill in others email
> Reset password for others (not the account in Step 1)

I think the originally reported issue is mistaken: 

> User should not allow using another user's email for reset password

For the reason because user was NEVER allowed to use another user's email to reset password. aka. If a user's username is `abc` with no email address or email address of `abc@abc.com`, it can never use forgot password for another account with another email `def@def.com`

So at most it is a minor UX issue (which the label do got it correctly)

****

However, I think @carmenlau 's latest proposal works the best and solved the minor ux problem.
