### ISSUE TITLE
Research AD FS

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-server#831]

**Comment by kiootic** [comment]
AD FS is some kind of OAuth/OIDC adaptor for traditional AD deployments (i.e. on Windows Server). As long as the AD FS is configured correctly in AD FS (e.g. exposed to Internet, correct client config), it seems rather standard as a OIDC OP.

**Comment by louischan-oursky** [comment]
When I implemented OIDC integration of Azure AD, I need to create a Azure AD tenant in the Azure portal. In there, I can create OAuth client application. Is AD FS created in the same way as a normal Azure AD tenant? How can the developer create OAuth client application?

**Comment by kiootic** [comment]
Since it's traditional AD (not Azure AD), you'll need to setup OAuth client application in the AD domain management console (which is Windows stuff).

You may find detailed OAuth client setup instruction here: https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/enabling-openid-connect-with-ad-fs

We'll need to have Windows Server with AD setup to test in real scenario.

**Comment by kiootic** [comment]
More details on OIDC implementation:
- OIDC discovery document at `https://[ADFS host]/adfs/.well-known/openid-configuration`
    - sample: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/master/tests/Microsoft.Identity.Test.Unit/Resources/OpenidConfiguration-OnPremise.json
    - seems pairwise.
- No tenant in ADFS.
- Authorization code flow: https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-openid-connect-oauth-flows-scenarios#authorization-code-grant-flow
- OAuth scopes: https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-openid-connect-oauth-concepts#scopes
    - seems `openid profile email` would suffice
- Sample ID token: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/679437a21132299d6582876cd0de882e89d8c163/tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs#L329-L342
  - seems should use `sub` instead of `oid`
