### ISSUE TITLE
Missing error message when re-verify code when back to previous page

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#920]
## Description:
After input the right code and continue to the next page, there is no error shown when user input the same code to verify again when back to the previous page.

## Steps to reproduce:
1. Input a valid email for sign up. Receive a code in the email.
2. Input the code in the text field, click continue(繼續)。
3. After direct to the setting password page, click back(<返回) button at the top left corner.
4. Input the same code received, click continue(繼續)。
5. See no error message shown and continue button is unresponsive

## Expected result:
Should show error message like 'This code has expired. Please reset password again'

**Comment by carmenlau** [comment]
<img width="646" alt="Screenshot 2021-01-28 at 11 27 00 AM" src="https://user-images.githubusercontent.com/388892/106073791-d39c7b80-615e-11eb-84b2-d0fe613eb94f.png">

@mr9dollars The error is not missing and shown in the testing video 🙈, I think the problem is the error translation is missing. I added back translation in the PR. Also I think we may want to have design for the error on the top? Currently we only show it on the top of the widget.

**Comment by mr9dollars** [comment]
Discussion:

1. Consider putting error message as snack bar error
2. Put input related error back into textfield error
