### ISSUE TITLE
Custom public domain feature UX improvement

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#945]
Solution after discussion:

1. Only 1 domain will be supported. Which is the public origin.
2. To avoid confusion, update auth ui to remove public origin configuration page. Instead, user can choose one active domain in custom domain page, which will be set into the public origin in app config.

=====

Original problem:

Tried adding a custom domain to Project House's production project, verified the domain, and set the new domain as the new public domain.

Saw 2 problems after doing that:
1. When I click the login/sign up button at kurious.live, I still see the domain name = https://kurious.authgearapps.com/login, not auth.kurious.live
2. The https://kurious.authgearapps.com/login?ui_locales=zh-Hant and https://auth.kurious.live/login page layout is broken, seems like the CSS is not loaded at all.

![image](https://user-images.githubusercontent.com/16920209/106440599-fd81d500-64b3-11eb-9263-8d0dce5adc1c.png)
![image](https://user-images.githubusercontent.com/16920209/106440752-27d39280-64b4-11eb-864b-005da325c6a1.png)

**Comment by carmenlau** [comment]
I think the problem is not custom domain not working. Now we only support one domain, after update the public origin, only the selected domain works. Developer needs to update the website to use the custom domain when configure SDK.

So we need to think of:

1. Do we want to support one domain only? I think we should, as we will use the selected public origin for all links e.g. reset password email. Support multiple domains is confusing. If we want to support multiple domains, we should fix it.
1. If we keep support one domain only, we should have better handling for the other domains or better guidance in portal.

**Comment by mr9dollars** [comment]
1. Think whether we support one domain.
2. Update docs
3. On portal, add reminders for user to update SDK.
4. If supporting one domain only, see if we need to add error message on the not supported domain.
