### ISSUE TITLE
Better Redirect URI support for no client ID use cases

### ISSUE THREAD

**Issue by mr9dollars** [authgear/authgear-server#980]
1. New attributes: `default_post_logout_redirect_uri` and `default_redirect_uri` which redirect users after logout / login respectively when there are no client ID (i.e. access [appname].authgearapps.com directly)
2. New attribute: `client_uri` which is per Client Applications, and it is the link for a "back to my app" button in Setting and Login page
    1. Setting page will accept `client_id` parameter and `post_logout_uri` parameter
3. New attribute: `default_client_uri`, which is the link for "back to my app" button in Setting and Login page without Client ID

**Comment by louischan-oursky** [comment]
I had a discussion with Carmen. We have a thought that we want to remove the logout button in the settings page. It is because for both mobile native app and web app, when the developer directs the user to the settings page, the developer will not expect the user to logout. Instead, most of the time the developer will display their own logout button in their app.

So settings page will not accept `post_logout_redirect_uri` anymore.

Thoughts? @chpapa

**Comment by chpapa** [comment]
> So settings page will not accept post_logout_redirect_uri anymore.

I think we can try it...
